config/routes.rb
Rails.application.routes.draw do

  get 'home/lpi_insurance'
  get 'home/gap_insurance'
  get 'home/vehicle_insurance'
  get 'home/break_down_insurance'


  get 'home/business_leasing'
  get 'home/business_finance'
  get 'home/personal_finance'
  get 'home/vehicle_finance'

  get 'business/search'
  post 'business/search'
  post 'home/application_saver'

  post 'home/upload_passport_file'
  post 'home/upload_file_visa'
  post 'home/upload_driver_licence_back'
  post 'home/upload_file'
  get 'home/index'

  get 'home/set_your_budget'

  get 'home/about_us'
  get 'home/how_it_works'
  get 'home/finance'
  
  get 'home/help_and_advice'
  get 'home/apply2'
  get 'home/apply3'
  get 'home/apply'
  get 'home/business_apply'
  get 'home/vehicle_apply'
  
  post 'home/apply_mail'

  root :to => 'home#index' 

end

app/views/template/_apply_form_step1.html.slim
li#application
    #about_information.col-md-12.col-xs-12
        .col-md-12.col-xs-12.about_information
            label.col-md-4.col-xs-12.control-label 
                | Driver Licence Imageas
            .col-md-8.col-xs-12.no-padding
                .col-md-12.text-center 
                    a#selected_import data-toggle="modal" data-target="#confirm" style="color:red; " Before upload please read!! 
                #licence_front.col-md-6.col-xs-12.text-center 
                    div class="dropzone_front needsclick dz-clickable"
                        div.dz-message.needsclick
                            img src="#{image_path('sample_front.png')}"
                            button#click_to_upload.btn.btn-primary  Click to Upload
                    a#front_capture_button.hidden-sm data-toggle="modal" data-target="#capture" style="color:red; "  Licence Front Capture
                #licence_back.col-md-6.col-xs-12.text-center 
                    div class="dropzone_back needsclick dz-clickable"
                        div.dz-message.needsclick
                            img src="#{image_path('sample_back.png')}"
                            button#click_to_upload.btn.btn-primary  Click to Upload
                    a#back_capture_button.hidden-sm data-toggle="modal" data-target="#back_capture" style="color:red;"  Licence Back Capture


        .col-md-12.col-xs-12.about_information
            label.col-md-4.col-xs-12.control-label Visa Image
            .col-md-8.col-xs-12.no-padding
                div class="visa_dropzone needsclick dz-clickable"
                    div.dz-message.needsclick
                        p Upload here Visa Image 
                        small 
                            | (.png .jpg 2MB)


        .col-md-12.col-xs-12.about_information
            label.col-md-4.col-xs-12.control-label Passport Image
            .col-md-8.col-xs-12.no-padding
                div class="passport_dropzone needsclick dz-clickable"
                    div.dz-message.needsclick
                        p Upload here Passport Image 
                        small 
                            | (.png .jpg 2MB)



        .col-md-12.col-xs-12.about_information
            label.col-md-4.col-xs-12.control-label 
                | Title
                span * 
            .col-md-8.col-xs-12.no-padding 
                = render partial: 'template/select_tag_form', locals: {select_tag_data: ["Mr", "Mrs", "Miss", "Ms"], id_name: "title",is_other: false, ul_class: "select_form_tag"}

        .col-md-12.col-xs-12.about_information
            label.col-md-4.col-xs-12.control-label  
                | Name
                span * 
            input#first_name.col-md-2.col-sm-12.col-xs-12.apply.required[name="first_name" data-validation="required" placeholder="First name" type="text" required="true"]
            input#middle_name.col-md-2.col-sm-12.col-xs-12.apply[name="first_name" placeholder="Middle name " type="text" ]
            input#sur_name.col-md-2.col-xs-12.apply.required[name="first_name" data-validation="required" placeholder="Sur name" type="text" required="true"]

        .col-md-12.about_information
            label.col-md-4.col-xs-12.control-label 
                | E-mail address
                span * 
            .col-md-8.col-xs-12.no-padding 
                input#e_mail_address.col-md-12.col-xs-12.apply.form-control name="e_mail_address" type="email" required="true" placeholder="e-mail"

        .col-md-12.about_information
            label.col-md-4.col-xs-12.control-label 
                | Date of birth
                span * 
            .col-md-8.col-xs-12.no-padding 
                input#date_of_birth.col-md-12.col-xs-12.apply.form-control.required.input-mask[data-validation="required" data-mask="99/99/9999" placeholder="dd/mm/yyyy" required="true"]


        .col-md-12.about_information
            label.col-md-4.col-xs-12.control-label 
                | Gender
                span * 
            .col-md-8.col-xs-12.no-padding 
                = render partial: 'template/select_tag_form', locals: {select_tag_data: ["male", "female", "unknown"], id_name: "gender",is_other: false, ul_class: "select_form_tag"}


    #material_information.col-md-12.col-xs-12
        .col-md-12.material_information
            label.col-md-4.col-xs-12.control-label 
                | Material status
                span * 
            .col-md-8.col-xs-12.no-padding 
                = render partial: 'template/select_tag_form', locals: {select_tag_data: ["single", "married", "defacto", "divorced", "separated", "widowed", "unknown"], id_name: "material_status",is_other: false, ul_class: "select_form_tag"}

        .col-md-12.material_information
            label.col-md-4.col-xs-12.control-label 
                | Dependants count
            .col-md-8.col-xs-12.no-padding 
                input#dependentsCount.col-md-12.col-xs-12.apply.form-control type="number" placeholder="Dependants count" max="10" min="0"
        .col-md-12.material_information
            label.col-md-4.col-xs-12.control-label Dependants Age
            .col-md-8.col-xs-12.no-padding 
                input#dependentsAge.col-md-5.col-xs-12.apply.form-control pattern="\d*" type="number"  placeholder="Age 1"
                #depend_age_form.col-md-12.col-xs-12.no-padding 
        .col-md-12.material_information
            label.col-md-4.col-xs-12.control-label  
                | Phone number
                span * 
            .col-md-8.col-xs-12.no-padding 
                input#home_phone.col-md-12.col-xs-12.apply.form-control.required placeholder="Phone number"

        .col-md-12.material_information
            label.col-md-4.col-xs-12.control-label  
                | Mobile number
            .col-md-8.col-xs-12.no-padding 
                input#cell_mobile_phone.col-md-12.col-xs-12.apply.form-control placeholder="Mobile number"

        .col-md-12.material_information
            label.col-md-4.col-xs-12.control-label  
                | Work number
            .col-md-8.col-xs-12.no-padding 
                input#work_phone.col-md-12.col-xs-12.apply.form-control placeholder="Work number"




    #driver_information.col-md-12.col-xs-12
        .col-md-12.driver_information
            label.col-md-4.col-sm-12.col-xs-12.control-label 
                | Driver licence number
                span * 
            .col-md-8.col-xs-12.no-padding 
                input#driver_licence_number.col-md-12.col-xs-12.apply.form-control[data-validation="required" required="true"  placeholder="Driver licence number"]

        .col-md-12.driver_information
            label.col-md-4.col-sm-12.col-xs-12.control-label 
                | Driver licence version
                span * 
            .col-md-8.col-xs-12.no-padding 
                input#driver_licence_version.col-md-12.col-xs-12.form-control.apply[data-validation="required" required="true" placeholder="Driver licence version"]

        .col-md-12.driver_information
            label.col-md-4.col-sm-12.col-xs-12.control-label 
                | Driver licence country
                span * 

            .col-md-8.col-xs-12.no-padding 
                input#driver_licence_country.col-md-12.col-xs-12.apply.form-control[data-validation="required"  required="true" placeholder="Driver licence country"]

        .col-md-12.driver_information
            label.col-md-4.col-xs-12.control-label 
                | Driver licence type
                span * 

            .col-md-8.col-xs-12.no-padding 
                = render partial: 'template/select_tag_form', locals: {select_tag_data: ["Learners", "Restrictad", "International", "Full"], id_name: "driver_licence",is_other: false, ul_class: "select_form_tag"}


        .col-md-12.driver_information
            label.col-md-4.col-xs-12.control-label 
                | Driver licence expire date
                span * 
            .col-md-8.col-xs-12.no-padding 
                input#driver_licence_expire_date.col-md-12.col-xs-12.apply.form-control.required.input-mask[data-validation="required" data-mask="99/99/9999" placeholder="dd/mm/yyyy" required="true"]



        .col-md-12.driver_information
            label.col-md-4.col-xs-12.control-label 
                | Citizen ship
                span * 
            .col-md-8.col-xs-12.no-padding 
                input#citizen_ship.col-md-12.col-xs-12.apply.form-control.required[data-validation="required" required="true" placeholder="CITIZEN"]


        .col-md-12.driver_information
            label.col-md-4.col-xs-12.control-label 
                | Last entry date

            .col-md-8.col-xs-12.no-padding 
                input#last_entry_date.col-md-12.col-xs-12.apply.form-control.input-mask[ data-mask="99/99/9999" placeholder="dd/mm/yyyy" ]

        .col-md-12.driver_information
            label.col-md-4.col-xs-12.control-label 
                | Visa expire date

            .col-md-8.col-xs-12.no-padding 
                input#visa_expire_date.col-md-12.col-xs-12.apply.form-control.input-mask[ data-mask="99/99/9999" placeholder="dd/mm/yyyy" ]


        .col-md-12.driver_information
            label.col-md-4.col-xs-12.control-label 
                | Residential status
                span * 

            .col-md-8.col-xs-12.no-padding 
                = render partial: 'template/select_tag_form', locals: {select_tag_data: ["citizen", "resident", "work visa", "working holiday", "visitor visa", "student visa", "other"], id_name: "residential_status",is_other: false, ul_class: "select_form_tag"}


    #nearest_information.col-md-12.col-xs-12
        .col-md-12
            label.col-md-4.col-xs-12.control-label 
                | Nearest relative first name
                span *
            .col-md-8.col-xs-12.no-padding 
                input#nearest_first_name.col-md-12.col-xs-12.apply.form-control.required placeholder="First name" type="text" required="true" data-validation="required"
        .col-md-12
            label.col-md-4.col-xs-12.control-label 
                | Last name
                span *
            .col-md-8.col-xs-12.no-padding 
                input#nearest_last_name.col-md-12.col-xs-12.apply.form-control.required placeholder="Last name" type="text" required="true" data-validation="required"

        .col-md-12[style="position: inherit"]
            label.col-md-4.col-xs-12.control-label 
                | Address
                span * 
            .col-md-8.col-xs-12.no-padding 
                input#nearest_address.col-md-12.col-xs-12.apply.form-control.required[data-validation="required" placeholder="21A..." required="true"]

        .col-md-12[style="position: inherit"]
            label.col-md-4.col-xs-12.control-label 
                | Phone 
                span *
            .col-md-8.col-xs-12.no-padding 
                input#nearest_phone_number.col-md-12.col-xs-12.apply.form-control.required placeholder="phone number"

        .col-md-12[style="position: inherit"]
            label.col-md-4.col-xs-12.control-label 
                | Relationship
                span * 
            .col-md-8.col-xs-12.no-padding
                = render partial: 'template/select_tag_form', locals: {select_tag_data: ["friend","husband","wife","father","mother","son","daughter","brother","sister","grandfather","grandmother","grandson","granddaughter","uncle","aunt","cousin","nephew", "boyfrend", "girlfriend","niece","fatherInLaw","motherInLaw","brotherInLaw","sisterInLaw","defacto","other"], id_name: "relation_ship",is_other: false, ul_class: "select_form_tag"}

app/views/template/_apply_form_step2.html.slim
li#application
    #living_information.col-md-12.col-xs-12
        .col-md-12
            label.col-sm-4.col-xs-12.control-label 
                | Tenancy
                span * 
            .col-md-8.col-xs-12.no-padding 
                = render partial: 'template/select_tag_form', locals: {select_tag_data: ["Boarding", "Renting", "Living with Parent", "Living with Relative", "Owner Mortage", "Home owner FreeHold", "Other"], id_name: "tenancy_status",is_other: false, ul_class: "select_form_tag"}


        .col-md-12[style="position: inherit"]
            label.col-md-4.col-xs-12.control-label 
                | Current address
                span * 
            .col-md-8.col-xs-12.no-padding.no-padding 
                input#postal_address.col-md-12.col-xs-12.apply.required[data-validation="required" required="true" placeholder="21A..."] 

        .col-md-12
            label.col-md-4.col-xs-12.control-label 
                | How long have you lived at this address?
                span * 
            .col-md-8.col-xs-12.no-padding 
                = render partial: 'template/select_tag_form', locals: {select_tag_data: ["less than 1 year", "1 year", "2 year", "3 year"], id_name: "living_period",is_other: true, ul_class: "select_form_tag"}

        .col-md-12[style="position: inherit"]
            label.col-md-4.col-xs-12.control-label Previous address(if less than 2 years at current address)
            .col-md-8.col-xs-12.no-padding 
                input#previous_address.col-md-12.col-xs-12.apply[placeholder="21A..." type="text"]

        .col-md-12
            label.col-md-4.col-xs-12.control-label How long did you live at this address?
            .col-md-8.col-xs-12.no-padding 
                = render partial: 'template/select_tag_form', locals: {select_tag_data: ["less than 1 year","1 year", "2 year", "3 year"], id_name: "previous_living_period",is_other: true, ul_class: "select_form_tag"}


    #work_information.col-md-12.col-xs-12
        .col-md-12[style="position: inherit"]
            label.col-md-4.col-xs-12.control-label 
                | Current company
                span * 
            .col-md-8.col-xs-12.no-padding 
                input#current_company.col-md-12.col-xs-12.apply.required[data-validation="required" placeholder="Sample Inc" required="true"]

        .col-md-12[style="position: inherit"]
            label.col-md-4.col-xs-12.control-label 
                | Current Address
                span *
            .col-md-8.col-xs-12.no-padding 
                input#current_company_address.col-md-12.col-xs-12.apply.required[data-validation="required" placeholder="company Address" required="true"]


        .col-md-12[style="position: inherit"]
            label.col-md-4.col-xs-12.control-label 
                | Current Employer phone
                span * 
            .col-md-8.col-xs-12.no-padding 
                input#current_phone_number.col-md-12.col-xs-12.apply.required[data-validation="required" placeholder="(   )    -     "  required="true"]

        .col-md-12[style="position: inherit"]
            label.col-md-4.col-xs-12.control-label 
                | Current Occupation
                span * 
            .col-md-8.col-xs-12.no-padding 
                input#current_occupation.col-md-12.col-xs-12.apply.required[data-validation="required" placeholder="Web Director"  required="true"]



        .col-md-12[style="position: inherit"]
            label.col-md-4.col-xs-12.control-label 
                | Current Employer Type
                span * 
            .col-md-8.col-xs-12.no-padding 
                = render partial: 'template/select_tag_form', locals: {select_tag_data: ["fullTime","commissionEarner","contractWorker","selfEmployed","partTime","casual","seasonal","beneficiary","student","retire","unemployed"], id_name: "employtype",is_other: false, ul_class: "select_form_tag"}

        .col-md-12
            label.col-md-4.col-xs-12.control-label 
                | How long have you worked at this company?
                span *
            .col-md-8.col-xs-12.no-padding 
                = render partial: 'template/select_tag_form', locals: {select_tag_data: ["less than 1 year","1 year", "2 year", "3 year"], id_name: "how_long_work",is_other: true, ul_class: "select_form_tag"}


    #previous_work_information.col-md-12.col-xs-12
        .col-md-12[style="position: inherit"]
            label.col-md-4.col-xs-12.control-label Previous Company
            .col-md-8.col-xs-12.no-padding 
                input#previous_company.col-md-12.col-xs-12.apply[placeholder="Previous company"]

        .col-md-12[style="position: inherit"]
            label.col-md-4.col-xs-12.control-label 
                | Previous Company Occupation
            .col-md-8.col-xs-12.no-padding 
                input#previous_occupation.col-md-12.col-xs-12.apply[data-validation="required" placeholder="Web director" ]

        .col-md-12[style="position: inherit"]
            label.col-md-4.col-xs-12.control-label 
                | Previous Employer Type
            .col-md-8.col-xs-12.no-padding 
                = render partial: 'template/select_tag_form', locals: {select_tag_data: ["fullTime","commissionEarner","contractWorker","selfEmployed","partTime","casual","seasonal","beneficiary","student","retire","unemployed"], id_name: "previous_employtype",is_other: false, ul_class: ""}

        .col-md-12
            label.col-md-4.col-xs-12.control-label How long did you work at previous company
            .col-md-8.col-xs-12.no-padding 
                = render partial: 'template/select_tag_form', locals: {select_tag_data: ["1 year", "2 year", "3 year"], id_name: "how_long_work_previous",is_other: true, ul_class: ""}

app/views/template/_apply_form_step3.html.slim
li#application.col-md-12
    #nearest_information.col-md-12.col-xs-12
        .col-md-12
            p style="font-size: 1.3em;" Privacy Act 1993: I/We: 
            p a) warrant that the information provided in this application is true and correct; 
            p b) authorize Sky Finance Limited or any of its agents (“Sky Finance") to contact my/our employer, any credit agency and any other source (each a "Source") to obtain, check and exchange (both now and in the future) information in connection with this application and any agreement that I/we may hereafter enter into with Sky Finance; 
            p c) acknowledge that my/our signature on this application shall operate as an authority to each Source to provide Sky Finance with any information about me/us which Sky Finance may require in connection with this application or any such agreement; 
            p d) acknowledge that this application will form part of any agreement I/we may hereafter enter into with Sky Finance and that the authorization set out above will be deemed to be incorporated into that agreement; 
            p e) authorize Sky Finance or any related company to store and process the information provided in this application to contact you with product information, event invitations and/or customer care related material. 
            p f) You are entitled, under the provisions of the Privacy Act 1993, to: 
            p 　(a) have access to personal information held by Sky Finance about you; 
            p 　(b) request correction of any personal information held by Sky Finance about you; in either case in accordance with the provisions of that Act. 

            .col-md-12 style="padding-top: 20px;"
                .col-md-1.col-xs-12.no-padding 
                    = render partial: 'template/select_tag_form', locals: {select_tag_data: [""], id_name: "agree_conset_policy",is_other: false, ul_class: "select_form_tag"}
                p.col-md-11.col-xs-12 style="font-size: 1.3em;"
                    | I agree to the privacy statement

app/views/template/_apply_form_step4.html.slim
li#application
    #assets_information.col-md-12.col-xs-12
        .col-md-12
            label.col-md-4.col-xs-12.control-label 
                | Assets(how much do you own?)
                span *
            .col-md-8.col-xs-12.no-padding 
                input#assets_home.col-md-12.col-xs-12.apply placeholder="$Home" type="number" required="true"
                input#assets_furnishing.col-md-12.col-xs-12.apply placeholder="$Furnishing" type="number"  required="true"
                input#assets_bank_account.col-md-12.col-xs-12.apply placeholder="$Bank account" type="number" required="true"
                input#assets_car.col-md-12.col-xs-12.apply placeholder="$Car" type="number" required="true"
                input#assets_investments.col-md-12.col-xs-12.apply placeholder="$Investment" type="number" required="true"

            #assets_form.custome_form  
                .col-md-8.col-xs-12.col-md-offset-4.no-padding
                    input#other_assets_name.col-md-5.col-xs-5.apply placeholder="Asset name" type="text" name="key"
                    input#other_assets.col-md-5.col-xs-5.apply placeholder="$" type="number" name="value"

            #custom_assets.col-md-8.col-xs-12.col-md-offset-4.no-padding
                p#add_assets.col-md-10.col-xs-12.no-padding 
                    span ＋
                    | ADD INFORMATION

        .col-md-12
            label.col-md-4.col-xs-12.control-label Total
            .col-md-8.col-xs-12.no-padding 
                input#total_assets.col-md-5.apply placeholder="$" disabled="true" value="0"
                input#total_num_assets.col-md-5.apply placeholder="3" disabled="true" value="0" 


 
    #loans_information.col-md-12.col-xs-12
        .col-md-12
            label.col-md-12.col-xs-12.control-label 
                | How much do you want to borrow for your car?
                span *
            .col-md-12.col-xs-12.no-padding 
                input#how_much_borrow.col-md-8.col-xs-12.apply placeholder="$" type="number" required="true"
 
        .col-md-12
            label.col-md-12.col-xs-12.control-label 
                | How long are you planning to pay off the amount of your finance?
                span *
            .col-md-12.col-xs-12.no-padding 
                = render partial: 'template/select_tag_form', locals: {select_tag_data: ["1 year", "2 year", "3 year", "4 year", "5 year"], id_name: "how_long_pay_off",is_other: false, ul_class: "select_form_tag"}
                

app/views/template/_apply_form_step5.html.slim
li#application.a.liabilities
  .form-group
    .col-md-12
      #title_error.error-message[style="display:none"]
        p
          | Please select a title
      ol.col-md-12.col-sm-12.col-xs-12.no-padding
        li.col-md-6.col-xs-6
          .liability
            label#mortages.other-input
              strong
                span
                  | Mortages
            .form-group
              .col-md-12
                label.col-md-6.control-label.text-left
                  | Balance owed
                input#balance_owed.col-md-6.apply.required[placeholder="$"]
            .form-group
              .col-md-12
                label.col-md-6.control-label.text-left
                  | Monthly replayment
                input#monthly_replayment.col-md-6.apply.required[placeholder="$"]
            .form-group
              .col-md-12
                label.col-md-6.control-label.text-left
                  | Provider
                input#provider.col-md-6.apply.required[placeholder="$"]
            .text-right
              a#fase5.btn.btn-primary.btn-apply[name="6" style="visibility:hidden"]

        li.col-md-6.col-xs-6
          .liability
            label#personal_loan.other-input
              strong
                span
                  | Personal loan
            .form-group
              .col-md-12
                label.col-md-6.control-label.text-left
                  | Balance owed
                input#balance_owed.col-md-6.apply.required[placeholder="$"]
            .form-group
              .col-md-12
                label.col-md-6.control-label.text-left
                  | Monthly replayment
                input#monthly_replayment.col-md-6.apply.required[placeholder="$"]
            .form-group
              .col-md-12
                label.col-md-6.control-label.text-left
                  | Provider
                input#provider.col-md-6.apply.required[placeholder="$"]
            .text-right
              a#fase5.btn.btn-primary.btn-apply[name="6" style="visibility:hidden"]

        li.col-md-6.col-xs-6
          .liability
            label#credit_card_1.other-input
              strong
                span
                  | Credit card 1
            .form-group
              .col-md-12
                label.col-md-6.control-label.text-left
                  | Balance Owed
                input#balance_owed.col-md-6.apply.required[placeholder="$"]
            .form-group
              .col-md-12
                label.col-md-6.control-label.text-left
                  | Monthly replayment
                input#monthly_replayment.col-md-6.apply.required[placeholder="$"]
            .form-group
              .col-md-12
                label.col-md-6.control-label.text-left
                  | Provider
                input#provider.col-md-6.apply.required[placeholder="$"]
            .text-right
              a#fase5.btn.btn-primary.btn-apply[name="6" style="visibility:hidden"]

        li.col-md-6.col-xs-6
          .liability
            label.other-input[for="otherAmount"]
              strong
                span
                  | Credit card 2
            .form-group
              .col-md-12
                label.col-md-6.control-label.text-left
                  | Balance Owed
                input.col-md-6.apply.required[name="ird_number" placeholder="$"]
            .form-group
              .col-md-12
                label.col-md-6.control-label.text-left
                  | Monthly replayment
                input.col-md-6.apply.required[name="ird_number" placeholder="$"]
            .form-group
              .col-md-12
                label.col-md-6.control-label.text-left
                  | Provider
                input.col-md-6.apply.required[name="ird_number" placeholder="$"]
            .text-right
              a#fase5.btn.btn-primary.btn-apply[name="6" style="visibility:hidden"]

      .text-right
        .col-md-12
          a#apply_now.btn.btn-primary.btn-apply[name="6"]
            |  apply 

app/views/template/_header.html.slim
meta[http-equiv="Content-Type" content="text/html; charset=UTF-8"]
meta[name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no"]

app/views/template/_navheader.html.slim
nav
  .layout
    ul#fade-in.pc.dropmenu

      li
        a href="" Finance
        ul
            li.submenu
                a href="#{home_business_leasing_path}" Business leasing 
                a href="#{home_business_finance_path}" Business finance 
                a href="#{home_vehicle_finance_path}" Vehicle finance


      li
        a href="" Insurance
        ul
            li.submenu
                a href="#{home_lpi_insurance_path}" LPI Insurance
                a href="#{home_gap_insurance_path}" GAP Insurance 
                a href="#{home_vehicle_insurance_path}" Vehicle Insurance 
                a href="#{home_break_down_insurance_path}" Breakdown Insurance 


      li
        a href="#{home_help_and_advice_path}" Help&advice
      li
        a href="#{home_about_us_path}" About us

      li
        a style="display: -webkit-inline-box;"  href="https://www.facebook.com/skyfinance.co.nz/" target="_blank"
            img src="#{image_path('icon_w.png')}" style="width: 25px; float: none; padding: 0;vertical-align: middle; margin: 0px 5px;"
        a style="display: -webkit-inline-box;" href="https://www.instagram.com/skyfinance_nz/" target="_blank"
            img src="#{image_path('icon_i.png')}" style="width: 25px; float: none; padding: 0;vertical-align: middle; margin: 0px 5px;"
        a style="display: -webkit-inline-box;" href="https://web.wechat.com/" target="_blank"
            img src="#{image_path('icon_f.png')}" style="width: 25px; float: none; padding: 0;vertical-align: middle; margin: 0px 5px;"

        
  a.menu-trigger.sp
    span
    span
    span
  .gblnv_block.sp
    ul.gblnv_list
      li.active
        a href="#{home_index_path}" Home

      li.dDown
        span Finance
        ul
            li
                a href="#{home_business_leasing_path}" Business leasing 
                a href="#{home_business_finance_path}" Business finance 
                a href="#{home_vehicle_finance_path}" Vehicle finance


      li.dDown
        span Insurance
        ul
            li.submenu
                a href="#{home_lpi_insurance_path}" LPI Insurance
                a href="#{home_gap_insurance_path}" GAP Insurance 
                a href="#{home_vehicle_insurance_path}" Vehicle Insurance 
                a href="#{home_break_down_insurance_path}" Breakdown Insurance 



      li
        a href="#{home_help_and_advice_path}" Help&advice
      li
        a href="#{home_about_us_path}" About us


      li
        a style="display: -webkit-inline-box;" href="https://www.facebook.com/skyfinance.co.nz/" target="_blank"
            img src="#{image_path('icon_w.png')}" style="width: 60px; float: none; padding: 0;vertical-align: middle; margin: 0px 10px;"
        a style="display: -webkit-inline-box;" href="https://www.instagram.com/skyfinance_nz/" target="_blank"
            img src="#{image_path('icon_i.png')}" style="width: 60px; float: none; padding: 0;vertical-align: middle; margin: 0px 10px;"
        a style="display: -webkit-inline-box;" href="https://web.wechat.com/" target="_blank"
            img src="#{image_path('icon_f.png')}" style="width: 60px; float: none; padding: 0;vertical-align: middle; margin: 0px 10px;"




header.top
  .scroll-stop style="overflow-y: hidden; position: relative;"
    section class="main-section" 

      .container.main_top
        .col-md-12
            .col-md-6.col-xs-12.pull-right
                .col-md-12
                    img src="#{image_path('large_logo.png')}" 

               
 
            .top_about.col-md-6.col-xs-12
                h2 A.I process  
                h2 Quick application
                a href="#{home_apply2_path}"
                    btn.btn.btn-lg.btn-primary 
                        | Apply now 
                        span.arrow ▲
 
               

app/views/template/_select_tag_form.html.slim
ul id="#{id_name}" class="#{ul_class}"
    #form_tag_error.col-md-12.text-center style="display:none"
        p you must select this select form

    - select_tag_data.each do |g|
        li.btn.btn-gray.btn-rounded value="#{g}"
            a#tag 
                span.glyphicon.glyphicon-ok 
                | #{g}


    - if is_other == true
        li.btn.btn-gray.btn-rounded.other 
            a#tag
                span.glyphicon.glyphicon-ok 
                input style="color: #666666; text-align:center;" placeholder="Other"